### ISSUE TITLE
Banner

### ISSUE THREAD

**Issue by Onurhan1337** [anonistas/notya#13]
One of the best things about a CLI application is Banner.

 We want to create a great banner for Notya, it could be a banner similar to the example below.

<img width="300" src="https://user-images.githubusercontent.com/23141800/103461895-b2e52f80-4d32-11eb-9e4b-f35304ececfa.png" alt="Banner example" />

**Comment by theiskaa** [comment]
@Onurhan1337 When It'll appear? On calling only `notya`, and `notya help`?
And also we could add a simple command to show only banner - e.g `notya banner`

**Comment by Onurhan1337** [comment]
@theiskaa  A charming flag will greet us at the first opening of Notya.

it will be best for us to create a flag called ```notya-banner```. In other flags, it will be a better choice to not have a flag so that the user can have a comfortable experience.

**Comment by theiskaa** [comment]
@Onurhan1337 

```
  _   _   ___  _____ __   __  _    
 | \ | | / _ \|_   _|\ \ / / / \   
 |  \| || | | | | |   \ V / / _ \  
 | |\  || |_| | | |    | | / ___ \ 
 |_| \_| \___/  |_|    |_|/_/   \_\
```

Alternative

```
 _   _         _                 
| \ | |  ___  | |_  _   _   __ _ 
|  \| | / _ \ | __|| | | | / _` |
| |\  || (_) || |_ | |_| || (_| |
|_| \_| \___/  \__| \__, | \__,_|
                    |___/        
```
