### ISSUE TITLE
Version command

### ISSUE THREAD

**Issue by theiskaa** [anonistas/notya#52]
A simple command to display [current] version of the Notya.
```
> notya version
v0.1.2
```

**Note:** version instance could be found at {pkg/constants.go} as > `pkg.Version`

**Comment by theiskaa** [comment]
Since cobra has a default version command we do not need this anymore ...
So Sorry, @Melihemin 😂

**Comment by Melihemin** [comment]
> Since cobra has a default version command we do not need this anymore ... So Sorry, @Melihemin joy

No problem 😅
